#!/usr/bin/env bash
# stop-gate.sh — KIT-OWNED. DO NOT EDIT THIS FILE.
#
# Stop / SubagentStop: the harness's closing gate. Vendored and checksummed
# like kit-gates.sh (see its header), and run through a project-owned shim at
# `.claude/hooks/stop-gate.sh`. It was project-owned until kit 2.9.0, which is
# the shape `leak_gate` had before it drifted into ten implementations.
#
# Three tests. stderr is fed back to the agent as instructions; exit 2 blocks.
#   1. dirty marker  — the Edit/Write tools changed a file and verify has not
#                      run since. BLOCKS.
#   2. red record    — the last verify failed, or its record cannot be read.
#                      BLOCKS.
#   3. tree state    — the tree is not the one verify judged. OBSERVES by
#                      default (Decision 84): it logs what it would block.
#
# Why test 3 exists (horde brief hypersaw-009): tests 1 and 2 trust a marker
# only two tools set and a record a new worktree does not have. An edit made
# through the shell (a generator, sed, a patch, a merge, a cherry-pick), or any
# edit where verify never ran, passed both, and so did a commit made after a
# green record.
#
# Test 3 passes when the tree's fingerprint (`kit_tree_hash`) equals EITHER
#   - the one `record` stored: this is the tree verify judged; or
#   - the tree where this branch left the default branch: there is no local
#     work here to verify. That holds whatever an old record says, so a pull,
#     a stash or a switch back to the default branch never blocks a session
#     that changed nothing.
# Anything else is unverified work. A clean checkout of a branch nobody
# verified HERE is in that class on purpose (it matches horde's own fix); each
# event records whether the tree was clean and pushed, so that rule can be
# revisited with a week of data instead of an argument.
#
# MODE: the shim may export KIT_STOP_GATE_MODE=deny to make test 3 block in one
# repo. The fleet default flips only by a kit release with a signed GATE-CHANGE.
set -uo pipefail

INPUT=$(cat)
# Prevent infinite loops: if we already blocked once this stop cycle, allow.
ACTIVE=$(printf '%s' "$INPUT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("stop_hook_active",False))' 2>/dev/null || echo "False")
[ "$ACTIVE" = "True" ] && exit 0

# Where this file lives, resolved BEFORE the `cd` below: invoked by a relative
# path from a subdirectory, the path stops resolving once the directory
# changes, and the gate could not find kit-gates.sh beside it.
SELF_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)

# A hook starts in the session's current directory, which may be a
# subdirectory after a `cd`. Every path below is relative to the repo root:
# from elsewhere the record was not found (a RED record passed) and only that
# subdirectory was fingerprinted.
TOP=$(git rev-parse --show-toplevel 2>/dev/null) && cd "$TOP"

HARNESS_DIR="${HARNESS_DIR:-.harness}"
REC="$HARNESS_DIR/last-verify.json"
RUN="Run ./verify fast (or full, if closing a queue item) and report the output verbatim before finishing."

if [ -f "$HARNESS_DIR/dirty" ]; then
  echo "Harness gate: edits exist that have not been verified. $RUN" >&2
  exit 2
fi

WANT=""
if [ -f "$REC" ]; then
  # One read gives both fields. A record that cannot be parsed is RED, not
  # green: "unreadable" used to fall back to exit 0, so a corrupt record of a
  # failed run let the session end.
  READ=$(python3 -c 'import json,sys
d = json.load(open(sys.argv[1]))
print(int(d.get("exit", 0)), d.get("tree") or "-")' "$REC" 2>/dev/null || echo "unreadable -")
  EXIT=${READ%% *}; WANT=${READ#* }; [ "$WANT" = "-" ] && WANT=""
  if [ "$EXIT" = "unreadable" ]; then
    echo "Harness gate: the last verify record cannot be read, so it proves nothing. $RUN" >&2
    exit 2
  fi
  if [ "$EXIT" != "0" ]; then
    echo "Harness gate: last oracle run was RED (./verify report). Fix or revert before finishing; do not end on red. If the failure is out of scope, say so explicitly and record it as an open question." >&2
    exit 2
  fi
fi

# --- test 3: is this the tree verify judged? --------------------------------
[ -n "$TOP" ] || exit 0                                         # not a repository
. "$SELF_DIR/kit-gates.sh"

CUR="" BASE_TREE="" MAN=""
cleanup() { [ -n "$MAN" ] && rm -f "$MAN"; }
trap cleanup EXIT

changed() { # paths whose entry differs between two `git ls-files -s` lists
  awk -F'\t' 'NR==FNR { a[$2]=$1; next } { b[$2]=$1 }
              END { for (p in a) if (a[p] != b[p]) print p
                    for (p in b) if (!(p in a)) print p }' "$1" "$2" 2>/dev/null | sort
}

finding() { # finding <why-slug> <message> <file list>
  local n; n=$(printf '%s' "$3" | grep -c . || true)
  if [ "${KIT_STOP_GATE_MODE:-observe}" = deny ]; then
    {
      echo "Harness gate: $2"
      [ -n "$3" ] && printf '%s\n' "$3" | head -5 | sed 's/^/  /'
      [ "$n" -gt 5 ] && echo "  … and $((n - 5)) more"
      echo "$RUN"
    } >&2
    exit 2
  fi
  # Observe: one line in the fleet event log, positions and verdicts only (a
  # count, never file names). `clean` = everything is committed; `pushed` =
  # that commit is on a remote. Together they separate "unverified work" from
  # "a checkout nobody verified here", which is what a reader needs to judge
  # whether a would-deny was a false one. Written only where the log already
  # exists, so CI and machines without the oversight hooks are left alone.
  local d="${KIT_FLEET_DIR:-$HOME/.claude/fleet}" repo clean=false pushed=false
  [ -n "$CUR" ] && [ "$CUR" = "$(git rev-parse -q --verify 'HEAD^{tree}' 2>/dev/null)" ] && clean=true
  [ -n "$(git branch -r --contains HEAD 2>/dev/null | head -1)" ] && pushed=true
  # The MAIN repo's name, even from a worktree: a worktree's own folder name
  # (agent-…) says nothing about which repo the finding belongs to.
  repo=$(basename "$(dirname "$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)")" 2>/dev/null | LC_ALL=C tr -cd 'A-Za-z0-9._-')
  [ -d "$d" ] && printf '{"at":"%s","clean":%s,"event":"would-deny","files":%d,"gate":"stop-gate","pushed":%s,"repo":"%s","why":"%s"}\n' \
    "$(date -u +%FT%TZ)" "$clean" "$n" "$pushed" "${repo:-unknown}" "$1" >> "$d/events.jsonl" 2>/dev/null
  exit 0
}

MAN=$(mktemp "${TMPDIR:-/tmp}/kit-stop.XXXXXX") || MAN=""
CUR=$(kit_tree_hash "$MAN") || CUR=""
[ -n "$CUR" ] || finding "no-fingerprint" "could not fingerprint the working tree, so it cannot be compared with what ./verify judged." ""

[ -n "$WANT" ] && [ "$CUR" = "$WANT" ] && exit 0

# Where this branch left the default branch. Read from origin/HEAD, not assumed
# to be `main`; most clones have no origin/HEAD, so main and master are tried
# next. With no remote at all the base is HEAD, so only uncommitted changes
# are seen there. That limit is stated, not hidden.
REF=$(git symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null || true)
if [ -z "$REF" ]; then
  for r in origin/main origin/master; do
    git rev-parse -q --verify "$r" >/dev/null 2>&1 && { REF="$r"; break; }
  done
fi
BASE=""
[ -n "$REF" ] && BASE=$(git merge-base HEAD "$REF" 2>/dev/null || true)
# A repo with no commits has no HEAD: compare against the empty tree.
BASE_TREE=$(git rev-parse -q --verify "${BASE:-HEAD}^{tree}" 2>/dev/null || git hash-object -t tree /dev/null)
[ "$CUR" = "$BASE_TREE" ] && exit 0

if [ -n "$WANT" ] && [ -s "$HARNESS_DIR/last-verify.tree" ] && [ -n "$MAN" ]; then
  finding "changed-after-verify" "the tree changed after the last ./verify:" \
    "$(changed "$HARNESS_DIR/last-verify.tree" "$MAN")"
fi
SLUG="never-verified"; MSG="./verify has not run on this tree. Changed since it left the default branch:"
[ -n "$WANT" ] && { SLUG="changed-after-verify"; MSG="the tree is not the one the last ./verify judged. Changed since it left the default branch:"; }
finding "$SLUG" "$MSG" "$(git diff --name-only "$BASE_TREE" HEAD 2>/dev/null; git status --porcelain 2>/dev/null | cut -c4-)"
